include ../.utils/setup.mk

MODULE_NAME := i3 

install-deps :=
setup-deps :=

install:

setup:
	@dir ${XDG_CONFIG_HOME}/i3
	@symlink ${CWD}/config ${XDG_CONFIG_HOME}/i3/config

teardown:

uninstall:

