include ../.utils/setup.mk

MODULE_NAME := regorith

install-deps :=
setup-deps :=

install:

setup:
	@dir ${XDG_CONFIG_HOME}/regorith/{i3,}
	@symlink ${CWD}/regolith/i3/* ${XDG_CONFIG_HOME}/regorith/i3

teardown:

uninstall:

