#!/usr/bin/env python3

import json

mapping = {
    "splitv": "V",
    "splith": "H",
    "stacked": "S",
    "tabbed": "T",
}

def dump_layout(root):
    if not "layout" in root:
        return ""

    layout = mapping[root["layout"]]
    s = f"{layout}("
    for node in root["nodes"]:
        s += dump_layout(node)
    s += ")"

    return s

try:
    lines = []
    while True:
        line = input().strip()
        if line.startswith("//"):
            continue
        if line == "":
            line = ","
        lines.append(line)
except EOFError:
    pass

data = "[" + "".join(lines)[:-1] + "]"
tree = json.loads(data)

print(",".join([dump_layout(root) for root in tree]))
